# Generated by Django 4.1.3 on 2022-11-23 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_sider_url_sider_descript_sider_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='customer_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='reviews',
            name='post',
            field=models.CharField(default='', max_length=300),
        ),
    ]
