# Generated by Django 4.1.3 on 2022-11-24 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_product_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='labels',
            field=models.CharField(choices=[('HOT', 'HOT'), ('NEW', 'NEW'), ('SALE', 'SALE')], max_length=100),
        ),
    ]
