# Generated by Django 4.1.3 on 2022-11-26 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_product_labels'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('slug', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=100)),
                ('review', models.TextField()),
                ('star', models.IntegerField(default=1)),
            ],
        ),
    ]
