# Generated by Django 4.1.3 on 2022-12-03 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='trueprice',
            field=models.IntegerField(default=0),
        ),
    ]
