# Generated by Django 4.1.3 on 2022-12-04 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
