# Generated by Django 4.1.3 on 2022-12-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_about_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=300)),
                ('subject', models.CharField(max_length=500)),
                ('company', models.CharField(max_length=300)),
                ('message', models.TextField()),
            ],
        ),
    ]
