# Generated by Django 4.1.3 on 2022-12-05 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_billingaddress_shippingaddress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
