# Generated by Django 4.1.3 on 2022-12-05 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_delete_shippingaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialnotes', models.TextField()),
                ('s_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.billingaddress')),
            ],
        ),
    ]
