# Generated by Django 4.1.3 on 2022-12-05 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_shippingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='username',
            field=models.CharField(default='', max_length=300),
        ),
    ]
