# Generated by Django 4.1.3 on 2022-12-05 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_billingaddress_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='username',
            field=models.CharField(default='', max_length=300),
        ),
    ]
