# Generated by Django 4.1.3 on 2022-12-16 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_remove_order_user_order_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='slug',
            field=models.CharField(default='', max_length=300),
        ),
    ]
