# Generated by Django 4.1.3 on 2022-12-16 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_order_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='slug',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
