# Generated by Django 4.1.3 on 2022-12-16 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_orderitem_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='slug',
        ),
    ]
