# Generated by Django 4.1.3 on 2022-12-18 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_remove_order_slug_remove_orderitem_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='message',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_id',
        ),
    ]
